animation:
  blink_duration: 0.2
  blink_interval: 3.0
  emotion_transition_time: 0.5
assets:
  animations_dir: src/assets/animations
  emotions_dir: src/assets/eyes
debug:
  enabled: true
  font_size: 24
display:
  brightness: 100
  contrast: 50
  fps: 30
  height: 480
  saturation: 50
  width: 800
emotion:
  min_confidence: 0.5
  model_path: src/models/emotion/emotion_model.h5
emotion_detection:
  confidence_threshold: 0.6
  emotions:
  - happy
  - sad
  - angry
  - surprised
  - neutral
  model_path: src/models/emotion/emotion_net
face:
  min_confidence: 0.5
  model_path: src/models/face/haarcascade_frontalface_default.xml
face_detection:
  min_neighbors: 5
  min_size: [30, 30]
  model_path: src/models/face/haarcascade_frontalface_default.xml
  scale_factor: 1.1
llm:
  context_window: 2048
  max_tokens: 512
  model_path: src/models/llm/tinyllama
  temperature: 0.7
  top_p: 0.9
logging:
  file: src/logs/eve2.log
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  level: INFO
voice:
  energy_threshold: 1000
  non_speaking_duration: 0.5
  pause_threshold: 0.8
  phrase_threshold: 0.3
  sample_rate: 16000
