# EVE2 Configuration

# Display settings
display:
  width: 800
  height: 480
  fps: 30
  rotation: 0
  hardware_display: true

# Face detection settings
face:
  detection_interval: 0.1  # seconds
  min_confidence: 0.6
  model_path: "models/face_detection"
  known_faces_path: "models/known_faces"

# Emotion detection settings
emotion:
  model_path: "models/emotion_detection"
  detection_interval: 0.2  # seconds
  min_confidence: 0.5

# Voice settings
voice:
  sample_rate: 16000
  channels: 1
  chunk_size: 1024
  energy_threshold: 300
  dynamic_energy_threshold: true
  pause_threshold: 0.8
  phrase_threshold: 0.3
  non_speaking_duration: 0.5

# LLM settings
llm:
  model_path: "models/llm"
  max_tokens: 100
  temperature: 0.7
  top_p: 0.9
  repetition_penalty: 1.2

# Asset paths
assets:
  sprites:
    neutral: "assets/sprites/neutral.png"
    happy: "assets/sprites/happy.png"
    sad: "assets/sprites/sad.png"
    angry: "assets/sprites/angry.png"
    surprised: "assets/sprites/surprised.png"
    sleepy: "assets/sprites/sleepy.png"

# Camera Settings
camera:
  device_index: 0
  resolution:
    width: 800
    height: 480
  fps: 30

# Face Recognition Settings
face_recognition:
  model_path: models/face/face_detection_model
  confidence_threshold: 0.6
  database_path: data/faces.db

# Emotion Detection Settings
emotion_detection:
  model_path: models/emotion/emotion_model
  emotions:
    - neutral
    - happy
    - sad
    - angry
    - surprised
    - sleepy

# Language Model Settings
llm:
  model_path: models/llm/tinyllama-1.1b-chat-v1.0.Q4_K_M.gguf
  context_window: 2048
  max_tokens: 512
  temperature: 0.7

# Logging Settings
logging:
  level: INFO
  file: logs/eve.log
  max_size: 10485760  # 10MB
  backup_count: 5 